# Generated by Django 4.2.13 on 2024-05-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_id', models.CharField(max_length=255)),
                ('sentence', models.TextField()),
                ('file_path', models.FileField(upload_to='records/')),
                ('status', models.CharField(default='unread', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
